"""add_full_name_and_is_active_to_users

Revision ID: d81978de9124
Revises: fec1613bb76d
Create Date: 2026-07-01 06:28:41.553945+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81978de9124'
down_revision: Union[str, None] = 'fec1613bb76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    # Add is_active with a server default so existing rows get TRUE automatically
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
