"""update_search_history_model

Revision ID: fec1613bb76d
Revises: 0001
Create Date: 2026-06-19 17:42:11.877653+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec1613bb76d'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('status', sa.Text(), server_default='SUCCESS', nullable=False))
    op.add_column('search_history', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('search_history', sa.Column('row_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'row_count')
    op.drop_column('search_history', 'error_message')
    op.drop_column('search_history', 'status')
    # ### end Alembic commands ###
